file = open('Sample_File.txt','r')
print(file.read())
file.close()
file_write = open('Sample_File.txt', 'w')
file_write.write(" Ayaan Bin Farooq, Favourite Subject:Maths \n Umer Ejaz Favourite Subject:Biology \n Abdullah Nayaab Favourite Subject:Computer \n Chaudhry Bilal Favourite Subject:Physics")
file_write.close()
file_append = open('Sample_File.txt', 'a')
file_append.write("\nKhubaib Malik Favourite Subject:Urdu")
file_append.close()